sudo: false

language: java
jdk:
  - oraclejdk8

cache:
    directories:
    - $HOME/.m2

after_success:
        # - mvn cobertura:cobertura coveralls:report
    - mvn clean test jacoco:report coveralls:report
